### ISSUE TITLE
是否支持Windows

### ISSUE THREAD

**Issue by haig233** [sxyazi/free-hls#20]
## 概述

这里写你对 BUG 的概述

## 环境信息

- 系统版本：windows10
- 视频格式：mp4
- 视频编码：h264
- ffmpeg 版本：
- python 版本：Python 3.6.8
- tmp/command.sh 内容：`这里写文件内容`

## 重现步骤

1. 
2. 
3. 

## 附件

**日志内容：**

```bash
Traceback (most recent call last):
  File "up.py", line 131, in <module>
    main()
  File "up.py", line 92, in main
    command = command_generator(os.path.abspath(argv[1]))
  File "up.py", line 67, in command_generator
    rate         = bit_rate(file)
  File "up.py", line 58, in bit_rate
    return int(execstr(['ffprobe','-v','error','-show_entries','format=bit_rate','-of','default=noprint_wrappers=1:nokey=1',file]))
  File "G:\free-hls-master\utils.py", line 41, in execstr
    return exec(*args, **kwargs).decode('utf-8').strip()
  File "G:\free-hls-master\utils.py", line 28, in exec
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\haig233\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\haig233\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

**ffmpeg -formats：**

```bash
ffmpeg -formats 执行结果：

```

**图片（如果有）：**

```bash
图片地址：
```

**视频文件（如果有）：**

```bash
# 推荐使用 https://send.firefox.com 上传视频

视频下载地址：
```
目录结构：
![image.png](https://i.loli.net/2020/03/15/6yeukgFd3i9SKtJ.png)

**Comment by sxyazi** [comment]
Windows 使用需要添加 `ffmpeg.exe` 和 `ffprobe.exe` 文件的路径到 `PATH` 环境变量中，这是程序所依赖的必要文件。对于 Windows 系统添加完似乎需要重启终端才能生效。
